curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=1&sch_type=&sch_name=' > district1.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=2&sch_type=&sch_name=' > district2.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=3&sch_type=&sch_name=' > district3.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=4&sch_type=&sch_name=' > district4.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=5&sch_type=&sch_name=' > district5.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=6&sch_type=&sch_name=' > district6.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=7&sch_type=&sch_name=' > district7.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=8&sch_type=&sch_name=' > district8.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=9&sch_type=&sch_name=' > district9.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=10&sch_type=&sch_name=' > district10.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=11&sch_type=&sch_name=' > district11.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=12&sch_type=&sch_name=' > district12.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=13&sch_type=&sch_name=' > district13.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=14&sch_type=&sch_name=' > district14.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=15&sch_type=&sch_name=' > district15.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=16&sch_type=&sch_name=' > district16.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=17&sch_type=&sch_name=' > district17.html
curl 'http://www.chsc.hk/psp2017/sch_list.php?lang_id=2&frmMode=pagebreak&district_id=18&sch_type=&sch_name=' > district18.html
